package com.hcl.canceltrx.service;

import com.hcl.canceltrx.domain.ExternalOrderResponseDTO;
import com.hcl.canceltrx.model.ExternalOrderDtoVO;

/**
 * Generated by codegen
 * Genetated At : 2022-04-26T12:02:06.765 */
public interface OrdersService {
    /**
     * posApiRestExternalorderOrderPost 
     */
    ExternalOrderResponseDTO posApiRestExternalorderOrderPost(ExternalOrderDtoVO externalOrderDto);
}
