package com.hcl.order.api.service;

import com.hcl.order.api.domain.ExternalOrderResponseDTO;
import com.hcl.order.api.model.ExternalOrderDtoVO;

/**
 * Generated by codegen
 * Genetated At : 2022-04-26T12:16:01.278 */
public interface OrdersService {
    /**
     * posApiRestExternalorderOrderPost 
     */
    ExternalOrderResponseDTO posApiRestExternalorderOrderPost(ExternalOrderDtoVO externalOrderDto);
}
