package com.hcl.order.api.domain;

import java.io.Serializable;
import java.lang.String;

/**
 * Generated by codegen
 */
public class ExternalOrderPaymentDetailDTO implements Serializable {
    private String lastFour;

    private String transactionType;

    private String amount;

    private String paymentTypeStandardId;

    private String approvalCode;

    private String auth;

    private String tipAmount;

    private String batchId;

    private String transactionId;

    public String getLastFour() {
        return lastFour;
    }

    public void setLastFour(String lastFour) {
        	this.lastFour = lastFour;
    }

    public String getTransactionType() {
        return transactionType;
    }

    public void setTransactionType(String transactionType) {
        	this.transactionType = transactionType;
    }

    public String getAmount() {
        return amount;
    }

    public void setAmount(String amount) {
        	this.amount = amount;
    }

    public String getPaymentTypeStandardId() {
        return paymentTypeStandardId;
    }

    public void setPaymentTypeStandardId(String paymentTypeStandardId) {
        	this.paymentTypeStandardId = paymentTypeStandardId;
    }

    public String getApprovalCode() {
        return approvalCode;
    }

    public void setApprovalCode(String approvalCode) {
        	this.approvalCode = approvalCode;
    }

    public String getAuth() {
        return auth;
    }

    public void setAuth(String auth) {
        	this.auth = auth;
    }

    public String getTipAmount() {
        return tipAmount;
    }

    public void setTipAmount(String tipAmount) {
        	this.tipAmount = tipAmount;
    }

    public String getBatchId() {
        return batchId;
    }

    public void setBatchId(String batchId) {
        	this.batchId = batchId;
    }

    public String getTransactionId() {
        return transactionId;
    }

    public void setTransactionId(String transactionId) {
        	this.transactionId = transactionId;
    }
}
