package com.hcl.order.api.domain;

import java.io.Serializable;
import java.lang.Long;
import java.lang.String;

/**
 * Generated by codegen
 */
public class ResponseDataDTO implements Serializable {
    private Long customerQuoteTime;

    private String restaurantOrderNumber;

    private String orderId;

    private String orderStatus;

    private String responseMessage;

    public Long getCustomerQuoteTime() {
        return customerQuoteTime;
    }

    public void setCustomerQuoteTime(Long customerQuoteTime) {
        	this.customerQuoteTime = customerQuoteTime;
    }

    public String getRestaurantOrderNumber() {
        return restaurantOrderNumber;
    }

    public void setRestaurantOrderNumber(String restaurantOrderNumber) {
        	this.restaurantOrderNumber = restaurantOrderNumber;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        	this.orderId = orderId;
    }

    public String getOrderStatus() {
        return orderStatus;
    }

    public void setOrderStatus(String orderStatus) {
        	this.orderStatus = orderStatus;
    }

    public String getResponseMessage() {
        return responseMessage;
    }

    public void setResponseMessage(String responseMessage) {
        	this.responseMessage = responseMessage;
    }
}
