package com.hcl.order.api.service.impl;

import com.hcl.order.api.domain.ExternalOrderResponseDTO;
import com.hcl.order.api.model.ExternalOrderDtoVO;
import com.hcl.order.api.service.OrdersService;
import org.modelmapper.ModelMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Generated by codegen
 * Genetated At : 2022-04-26T12:16:04.131 */
@Service
@Transactional
class OrdersServiceImpl implements OrdersService {
    private ModelMapper modelMapper;

    @Autowired
    public void setmodelMapper(ModelMapper modelMapper) {
        this.modelMapper = modelMapper;
    }

    /**
     * posApiRestExternalorderOrderPost 
     * Genetated At : 2022-04-26T12:16:02.982 */
    public ExternalOrderResponseDTO posApiRestExternalorderOrderPost(
            ExternalOrderDtoVO externalOrderDto) {
        // TODO
        // add code snippet for business logic and use the object mapper for entity to model conversion
        // Entity entity=modelMapper.map(drinks,Entity.class);
        // com.hcl.order.api.domain.ExternalOrderResponseDTO dto=modelMapper.map(entity,com.hcl.order.api.domain.ExternalOrderResponseDTO.class);
        return new ExternalOrderResponseDTO();
    }
}
