package com.hcl.canceltrx.domain;

import java.util.List;
import java.util.ArrayList;
import java.lang.String;
import java.io.Serializable;
/**
 * Generated by codegen
 */
public class ExternalOrderResponseDTO implements Serializable {
	public List<com.hcl.canceltrx.domain.ResponseDataDTO> getResponseDataDTOs() {
		return responseDataDTOs;
	}

	private List<com.hcl.canceltrx.domain.ResponseDataDTO> responseDataDTOs = new ArrayList<com.hcl.canceltrx.domain.ResponseDataDTO>();

	public void setResponseDataDTOs(List<com.hcl.canceltrx.domain.ResponseDataDTO> responseDataDTOs) {
		this.responseDataDTOs = responseDataDTOs;
	}

	private String status;

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
}