package com.hcl.canceltrx.controller;

import com.hcl.canceltrx.domain.ExternalOrderResponseDTO;
import com.hcl.canceltrx.model.ExternalOrderDtoVO;
import com.hcl.canceltrx.service.OrdersService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Generated by codegen
 * Genetated At : 2022-04-26T12:02:10.195 */
@RestController
@RequestMapping("/v1")
@Validated
public class OrdersController {
    private OrdersService ordersService;

    @Autowired
    public void setOrdersService(OrdersService ordersService) {
        this.ordersService = ordersService;
    }

    /**
     * posApiRestExternalorderOrderPost 
     * Genetated At : 2022-04-26T12:02:08.099 */
    @PostMapping("/posApiRest/externalorder/order")
    public ExternalOrderResponseDTO posApiRestExternalorderOrderPost(
            @RequestBody ExternalOrderDtoVO externalOrderDto) {
        // TODO
        ExternalOrderResponseDTO externalOrderResponseDTO = ordersService.posApiRestExternalorderOrderPost(externalOrderDto);
        return externalOrderResponseDTO;
    }
}
