package com.hcl.order.api.model;

import java.io.Serializable;
import java.lang.String;

/**
 * Generated by codegen
 */
public class ExternalOrderCustomerDetailVO implements Serializable {
    private String country;

    private String firstname;

    private String city;

    private String addressType;

    private String postalCode;

    private String streetAddress1;

    private String unitNumber;

    private String streetAddress2;

    private String streetAddress3;

    private String deliveryInstruction;

    private String lastname;

    private String phoneNumber;

    private String customerId;

    private String state;

    private String email;

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        	this.country = country;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        	this.firstname = firstname;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        	this.city = city;
    }

    public String getAddressType() {
        return addressType;
    }

    public void setAddressType(String addressType) {
        	this.addressType = addressType;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(String postalCode) {
        	this.postalCode = postalCode;
    }

    public String getStreetAddress1() {
        return streetAddress1;
    }

    public void setStreetAddress1(String streetAddress1) {
        	this.streetAddress1 = streetAddress1;
    }

    public String getUnitNumber() {
        return unitNumber;
    }

    public void setUnitNumber(String unitNumber) {
        	this.unitNumber = unitNumber;
    }

    public String getStreetAddress2() {
        return streetAddress2;
    }

    public void setStreetAddress2(String streetAddress2) {
        	this.streetAddress2 = streetAddress2;
    }

    public String getStreetAddress3() {
        return streetAddress3;
    }

    public void setStreetAddress3(String streetAddress3) {
        	this.streetAddress3 = streetAddress3;
    }

    public String getDeliveryInstruction() {
        return deliveryInstruction;
    }

    public void setDeliveryInstruction(String deliveryInstruction) {
        	this.deliveryInstruction = deliveryInstruction;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        	this.lastname = lastname;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        	this.phoneNumber = phoneNumber;
    }

    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
        	this.customerId = customerId;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        	this.state = state;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        	this.email = email;
    }
}
