package com.hcl.order.api.model;

import java.util.List;
import java.util.ArrayList;
import java.lang.String;
import java.io.Serializable;
/**
 * Generated by codegen
 */
public class ExternalOrderResponseVO implements Serializable {
	public List<com.hcl.order.api.model.ResponseDataVO> getResponseDataVOs() {
		return responseDataVOs;
	}

	private List<com.hcl.order.api.model.ResponseDataVO> responseDataVOs = new ArrayList<com.hcl.order.api.model.ResponseDataVO>();

	public void setResponseDataVOs(List<com.hcl.order.api.model.ResponseDataVO> responseDataVOs) {
		this.responseDataVOs = responseDataVOs;
	}

	private String status;

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
}